### ISSUE TITLE
Gitlab mirror test failing on forks

### ISSUE THREAD

**Issue by tlunet** [Parallel-in-Time/pySDC#116]
Just updated my fork repository (https://github.com/tlunet/pySDC) to the latest version, but then it runs some test to check a "gitlab mirror", and it does not pass (see error log in https://github.com/tlunet/pySDC/runs/5378850003?check_suite_focus=true).
Seems to be some authentication issue with the gitlab mirror repository from Helmotz Codebase repo ... 

Should we try to fix it or just ignore ?

**Comment by pancetta** [comment]
Ingore or, better, delete the `.github/workflows/mirror_to_gitlavb.yml` file, i.e. [this](https://github.com/Parallel-in-Time/pySDC/blob/master/.github/workflows/mirror_to_gitlab.yml) one.

**Comment by pancetta** [comment]
I think I should rather restrict the execution to this repository. This way forks will simply ignore this workflow.. I’ll have a look at it asap.

**Comment by pancetta** [comment]
Look at the recent commit. I added [this line](https://github.com/Parallel-in-Time/pySDC/blob/83ac8b0c41395658cb5e204a5d67f0960261098e/.github/workflows/mirror_to_gitlab.yml#L9) which should stop the job from running on forks. Let me know if that does the trick.

**Comment by tlunet** [comment]
That's weird ... now it's the pytest before that fails : https://github.com/tlunet/pySDC/runs/5389320157?check_suite_focus=true

**Comment by pancetta** [comment]
That's a different issue... with the new quadrature, the error is much higher in the tests than they used to be. Since the tests take random values, sometimes the bounds are too strict, still. I have no idea what the new quadrature does this (need to set the bounds from ~`1E-14` to ~`1E-10`, it seems).

**Comment by tlunet** [comment]
Can't you just set a fixed random seed for the tests (at least, one that work). And btw, what do you mean by new quadrature ? Is it the optimized implementation I provided some time ago ?

**Comment by tlunet** [comment]
I'll try to look into it. But in the meantime, the mirror test passed on my development branch, so I guess this issue can be closed :wink:
