### ISSUE TITLE
Add project for adaptivity and error estimation

### ISSUE THREAD

**Issue by pancetta** [Parallel-in-Time/pySDC#122]
The new adaptivity feature in the controller(s) should be showcased in a dedicated project, including tests and documentation.

- [x] Create new project infrastructure (folder, test, docs)
- [x] Showcase adaptive SDC with and without HotRod (incl. tests and doc)
- [x] Showcase adaptive multi-step SDC with and without HotRod (incl. tests and doc)
- [x] Do all this in the parallel controller as well (incl. test and doc)

TBC.

**Comment by brownbaerchen** [comment]
We have finished point 3 here: https://github.com/Parallel-in-Time/pySDC/blob/cad17cd4bfcafd6b30474de5dddd145f272266a3/pySDC/projects/Resilience/HotRod.ipynb
Only the MPI implementations are missing.

**Comment by pancetta** [comment]
Can we close this?
