### ISSUE TITLE
Is `check_iteration_estimator` in the wrong place?

### ISSUE THREAD

**Issue by pancetta** [Parallel-in-Time/pySDC#155]
Can we integrate the function [check_iteration_estimator](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/implementations/controller_classes/controller_nonMPI.py#L84) into the new `convergence_controllers`? Maybe I'm wrong, but it looks very similar. What do you think, @brownbaerchen?

**Comment by brownbaerchen** [comment]
Yes, that was on my to-do list anyways. I'll make sure to get around to it soon

**Comment by pancetta** [comment]
Closed by #156
