### ISSUE TITLE
implement on GPU

### ISSUE THREAD

**Issue by RedBlack888** [Parallel-in-Time/pySDC#201]
dear, 

I want to know it is possible to implement on GPU, which is popular for parallel computing.

I mean finesweep can be computed by multiple GPU cores.

best

**Comment by pancetta** [comment]
Hi! Yes, you can run this on a GPU. We did first steps [here](https://github.com/Parallel-in-Time/pySDC/tree/master/pySDC/projects/GPU) using [CuPy](https://cupy.dev/). This is not yet able to run on multiple GPUs. For that we either need to use a multi-GPU solver (e.g. FFT) or couple multiple GPUs using mpi4py.

**Comment by RedBlack888** [comment]
@pancetta thanks for your advice. Best.
