### ISSUE TITLE
Test splines in collocation

### ISSUE THREAD

**Issue by pancetta** [Parallel-in-Time/pySDC#209]
Test [coverage does not look great](https://parallel-in-time.org/pySDC/coverage/d_8d0d803e4e125e5c_Collocation_py.html#t105) for the option `useSpline`. Can you write a test for this, @tlunet ?

**Comment by tlunet** [comment]
I don't know ... I basically copy-pasted what was in the original version to generate spline-based collocation (in particular for the minimal order). Had the feeling that this spline thing was mostly an experimental thing used in the `EquidistantSpline_Right` class. Do we really want to spend some time on it ?

**Comment by pancetta** [comment]
Absolutely not. But if we don't use these parts, then we also could remove them, no?

**Comment by tlunet** [comment]
That's you choice @pancetta , I guess :sweat_smile:. You are the one that originally implemented it, right ?

**Comment by pancetta** [comment]
Maaayyybeee.... anyway, if not used, let's throw them away. Me, you, anyone?

**Comment by tlunet** [comment]
Closed as #227 was merged
