### ISSUE TITLE
Test coverage of Lagrange.py

### ISSUE THREAD

**Issue by pancetta** [Parallel-in-Time/pySDC#212]
Looks like [Lagrange.py](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/core/Lagrange.py) could use [more tests](https://parallel-in-time.org/pySDC/coverage/d_8d0d803e4e125e5c_Lagrange_py.html). Any volunteers?

**Comment by tlunet** [comment]
Those part are mostly used if we need a large number of nodes (like > 1000), and were used for asymptotic analysis in an other project from where this code was copy-pasted. 

There is probably no need to write tests for it in pySDC, probably simplifying the implementation and keep only the `FAST` implementation of weight computation should be enough (with an error raised if there is a floating point error during weight computation, and no automatic switch to a stable implementation).

**Comment by pancetta** [comment]
Sounds good. You, me, someone?
