### ISSUE TITLE
Test missing for `communicate_convergence`

### ISSUE THREAD

**Issue by pancetta** [Parallel-in-Time/pySDC#218]
In the `CheckConvergence` class, the function `communicate_convergence` is [not called during tests](https://parallel-in-time.org/pySDC/coverage/d_c28af68f8f845bbd_check_convergence_py.html#t59). Fix, remove, shrug?

**Comment by brownbaerchen** [comment]
This function is tested in the van der Pol tests in the Resilience project where I check if MPI and non MPI versions do the same. 
I confirmed that this is the case locally by writing `raise` in the function and then running `pytest pySDC/tests/test_projects/test_resilience/test_vdp.py`. Are you sure that your report includes all tests and not just the non-MPI ones for instance? This function relies on the send and receive functions in the base convergence controller class, so these should also be tested here, contrary to what issue #211 says.

**Comment by pancetta** [comment]
Interesting.. so, issue #222 also surprised me. I wonder whether coverage does not play well with MPI stuff, then?

**Comment by brownbaerchen** [comment]
Coverage is tested in this matrix way in the CI pipeline. Are the reports merged after that at all? Without knowing what this really does, I would expect you obtain four different reports for the different environments (times how many versions of python are tested).

**Comment by pancetta** [comment]
Yes, [they are merged](https://github.com/Parallel-in-Time/pySDC/blob/master/.github/workflows/ci_pipeline.yml#L133). But who knows, maybe there's a problem there..

**Comment by pancetta** [comment]
I think I know what the problem. Will try to fix it asap.

**Comment by pancetta** [comment]
In case you wonder: lines like [these](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/tests/test_projects/test_parallelSDC/test_preconditioner_MPI.py#L15) are a problem, because with the `subprocess` construct `coverage.py` cannot see that these things are called. Not quite sure how to fix that, though.

**Comment by pancetta** [comment]
Fixed in https://github.com/Parallel-in-Time/pySDC/commit/729cb6913addd41d530ff3b54bb8292ff52ed77f
