### ISSUE TITLE
Test missing for `post_iteration_processing`

### ISSUE THREAD

**Issue by pancetta** [Parallel-in-Time/pySDC#219]
In the `EstimateEmbeddedErrorMPI` class, the function `post_iteration_processing` is [never called during tests](https://parallel-in-time.org/pySDC/coverage/d_c28af68f8f845bbd_estimate_embedded_error_py.html#t168). Fix, remove, ignore?

**Comment by brownbaerchen** [comment]
This is also tested in MPI tests, I confirmed locally just like in #218

**Comment by pancetta** [comment]
Fixed in https://github.com/Parallel-in-Time/pySDC/commit/729cb6913addd41d530ff3b54bb8292ff52ed77f
