### ISSUE TITLE
Test missing for `prepare_next_block`

### ISSUE THREAD

**Issue by pancetta** [Parallel-in-Time/pySDC#220]
In the `SpreadStepSizesBlockwiseMPI` class, the function `prepare_next_block` is [never called during tests](https://parallel-in-time.org/pySDC/coverage/d_c28af68f8f845bbd_spread_step_sizes_py.html#t84). Fix, remove, ignore?

**Comment by brownbaerchen** [comment]
Same, same #218

**Comment by pancetta** [comment]
Fixed in https://github.com/Parallel-in-Time/pySDC/commit/729cb6913addd41d530ff3b54bb8292ff52ed77f
