### ISSUE TITLE
desc = _cusparse.createDnVec(x.size, x.data.ptr, cuda_dtype) 

### ISSUE THREAD

**Issue by RedBlack888** [Parallel-in-Time/pySDC#272]
Dear, 

when I try to run '/playgrounds/Allen_Cahn/AllenCahn_contracting_circle_standard_integrators.py' and import the relative classes from '/implementations/problem_classes/AllenCahn_2D_FD_gpu.py' with the help of GPU.  A bug happened.

The version of python=3.7,  cuda is 10.2, and cupy version is 11.5.0 (which is installed by 'pip3 install cupy-cuda102 ').

There is a bug when solving the equations with CG method
`u -= cg(dg, g, x0=z, tol=self.params.lin_tol)[0]
`
the bug details as following:

```
cupy/cusparse.py", line 1344, in create
    desc = _cusparse.createDnVec(x.size, x.data.ptr, cuda_dtype)
```
```
  File "/home/works/pySDC/pySDC/implementations/problem_classes/AllenCahn_2D_FD_gpu.py", line 128, in solve_system
    u -= cg(dg, g, x0=z, tol=self.params.lin_tol)[0]
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/cupyx/scipy/sparse/linalg/_iterative.py", line 64, in cg
    r = b - matvec(x)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/cupyx/scipy/sparse/linalg/_interface.py", line 89, in matvec
    y = self._matvec(x)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/cupyx/scipy/sparse/linalg/_interface.py", line 282, in _matvec
    return self.__matvec_impl(x)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/cupyx/scipy/sparse/linalg/_iterative.py", line 374, in matvec
    desc_x = cusparse.DnVecDescriptor.create(x)
  File "/home/anaconda3/envs/py37/lib/python3.7/site-packages/cupy/cusparse.py", line 1344, in create
    desc = _cusparse.createDnVec(x.size, x.data.ptr, cuda_dtype)
AttributeError: 'memoryview' object has no attribute 'ptr'
```

It seems the cusparse x.data has no attribute 'ptr'

so, what is wrong, did you encounter the bug?

Best,
Hamilton

**Comment by pancetta** [comment]
Hi! Thanks for reporting! Can you please check if you are able to run the examples in the [GPU project](https://github.com/Parallel-in-Time/pySDC/tree/master/pySDC/projects/GPU)? I don’t know exactly what’s going on, but since we currently cannot run the GPU Code within the CI, this is uncharted territory for now. Also, can you test this with a different Python version (e.g. 3.10)?

**Comment by RedBlack888** [comment]
> Hi! Thanks for reporting! Can you please check if you are able to run the examples in the [GPU project](https://github.com/Parallel-in-Time/pySDC/tree/master/pySDC/projects/GPU)? I don’t know exactly what’s going on, but since we currently cannot run the GPU Code within the CI, this is uncharted territory for now. Also, can you test this with a different Python version (e.g. 3.10)?

python version 3.10 encounter the same bug information as python3.7.

**Comment by RedBlack888** [comment]
> Hi! Thanks for reporting! Can you please check if you are able to run the examples in the [GPU project](https://github.com/Parallel-in-Time/pySDC/tree/master/pySDC/projects/GPU)? I don’t know exactly what’s going on, but since we currently cannot run the GPU Code within the CI, this is uncharted territory for now. Also, can you test this with a different Python version (e.g. 3.10)?

when I try to run  python3 'heat.py'  in [GPU projec](https://github.com/Parallel-in-Time/pySDC/tree/master/pySDC/projects/GPU)
Runtime CPU: 0.21493608877062798
Traceback (most recent call last):
  File "/home/pySDC/pySDC/projects/GPU/heat.py", line 101, in <module>
    main()
  File "/home/pySDC/pySDC/projects/GPU/heat.py", line 93, in main
    uend_gpu, stats_gpu = controller.run(u0=uinit, t0=t0, Tend=Tend)
  File "/home/pySDC/pySDC/implementations/controller_classes/controller_nonMPI.py", line 119, in run
    self.restart_block(active_slots, time, u0)
  File "/home/pySDC/pySDC/implementations/controller_classes/controller_nonMPI.py", line 200, in restart_block
    self.MS[p].init_step(u0)
  File "/home/pySDC/pySDC/core/Step.py", line 271, in init_step
    self.levels[0].u[0] = P.dtype_u(u0)
  File "/home/pySDC/pySDC/implementations/datatype_classes/cupy_mesh.py", line 40, in __new__
    raise NotImplementedError(type(init))
NotImplementedError: <class 'pySDC.implementations.datatype_classes.mesh.mesh'>

**Comment by pancetta** [comment]
Hm, strange. Looks like there was a mix-up between two different versions of the code. I also saw a bug when trying to run the code, but a different one. That I fixed this now and I'm able to run both examples on [Google Colab](https://colab.research.google.com/drive/1wqrGFLAgR_NJ6vS8lpOoxhdS8M-TMXFX?usp=sharing). Btw. if you run this the first time the GPU code is really slow. Run it again and you see speedup.

**Comment by RedBlack888** [comment]
> Hm, strange. Looks like there was a mix-up between two different versions of the code. I also saw a bug when trying to run the code, but a different one. That I fixed this now and I'm able to run both examples on [Google Colab](https://colab.research.google.com/drive/1wqrGFLAgR_NJ6vS8lpOoxhdS8M-TMXFX?usp=sharing). Btw. if you run this the first time the GPU code is really slow. Run it again and you see speedup.
> 
> Anyway, since it runs on Google Colab, I assume the only difference could be in the packages installed. Did you see/use the `environment-cupy.yml` in the `etc` folder? With conda or micromamba this should give you a working environment, if you have CUDA in v11.

Appreciate your advice. 
It works for python3.8.10 with cuda 10.2 and cupy 11.4. 
The packages as following, hope it is useful for others. 

Best!

```
Package      Version
------------ ---------
certifi      2022.12.7
cupy-cuda102 11.4.0
dill         0.3.6
fastrlock    0.8.1
mkl-fft      1.3.1
mkl-random   1.2.2
mkl-service  2.4.0
numpy        1.24.0
pip          22.3.1
scipy        1.9.3
setuptools   65.6.3
six          1.16.0
wheel        0.37.1
```

**Comment by RedBlack888** [comment]
The scripts in folder 'projects/GPU' works, 

`pySDC/playgrounds/Allen_Cahn$ python3 AllenCahn_contracting_circle_standard_integrators.py` still has bugs,

```
Traceback (most recent call last):
  File "AllenCahn_contracting_circle_standard_integrators.py", line 231, in <module>
    main_error()
  File "AllenCahn_contracting_circle_standard_integrators.py", line 226, in main_error
    err, _, _ = run_CrankNicholson(t0=t0, dt=0.001 / 64, Tend=Tend)
  File "AllenCahn_contracting_circle_standard_integrators.py", line 129, in run_CrankNicholson
    u = problem.u_exact(t0)
  File "/home/pySDC/pySDC/implementations/problem_classes/AllenCahn_2D_FD_gpu.py", line 175, in u_exact
    me[:] = cp.tanh((self.params.radius - cp.sqrt(mx**2 + my**2)) / (cp.sqrt(2) * self.params.eps))
  File "cupy/_core/core.pyx", line 1473, in cupy._core.core._ndarray_base.__array__
TypeError: Implicit conversion to a NumPy array is not allowed. Please use `.get()` to construct a NumPy array explicitly.
```

**Comment by pancetta** [comment]
This playground (like much of pySDC for now) does not support GPU problem classes out of the box, I'm afraid. You can make it work by changing line 7 to
```
from pySDC.implementations.datatype_classes.cupy_mesh import cupy_mesh, imex_cupy_mesh
```
I just tested with Google Colab and it looks like it's doing something. Note that it's missing a reference solution, i.e. it fails at the end of the run.

**Comment by RedBlack888** [comment]
> 

yes.  The format are different.

type of `uref` load from` .npz `file : is `<class 'numpy.ndarray'>`; while type of `u` is `<class 'pySDC.implementations.datatype_classes.cupy_mesh.cupy_mesh'>`.

I do not know how to make them consistent.

Best,

**Comment by pancetta** [comment]
You can convert CuPy arrays to NumPy arrays, see https://docs.cupy.dev/en/stable/reference/ndarray.html. If you do that after the run, this should do the trick.

**Comment by RedBlack888** [comment]
> You can convert CuPy arrays to NumPy arrays, see https://docs.cupy.dev/en/stable/reference/ndarray.html. If you do that after the run, this should do the trick.

`    u = cp.ndarray.get(u)` works. 

Thanks for your advice.

Bese!
