### ISSUE TITLE
maxiter=0 and maxiter=1 give identical results

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/pySDC#29]
For the fast-wave slow-wave problem at least, it seems that there is no difference between setting *maxiter=0* and *maxiter=1* (for SDC, using *num_proc=1*) since reported errors are identical in all digits.

Also, the stability plot in both cases is different from that of IMEX Euler: it should be stable up to 2.0 on the slow axis, because *dt=1.0* and forward Euler is stable until 2.0/abs(a) (cf. attached plot).

Is this expected behaviour?

*NOTE*: Compared wrong things here, plot showed standard IMEX, not fast-wave slow-wave. For the latter, there are still differences but they are much smaller.

**Comment by pancetta** [comment]
Question 1: yeah, well, the sweeper shoots first and asks then (i.e. check if k >= K comes after the first sweep)..
Question 2: don't know.. the plot shows IMEX euler, right?

**Comment by danielru** [comment]
Yes, this is from my own lightweight, scalar-only IMEX Euler. But since SDC always does something, even for *max_iter=0*, it probably is not surprising that we do not get the same figure.

**Comment by pancetta** [comment]
Hm.. but with max_iter = 0 or  = 1 only one iteration is done, using the initial condition as initial guess everywhere. So, wouldn't we expect that we have an IMEX Euler then? Would we? Or not? Hell, what do I know...

**Comment by danielru** [comment]
Depends: before the very first iteration, do you spread the initial condition and update the quadrature terms? If so, the first sweep is no longer equivalent to the base method alone.

**Comment by pancetta** [comment]
Yeah, that's probably it. SDC starts with spreading the data and integrating the RHS, so no, that's not the base method anymore.

**Comment by danielru** [comment]
The argument I made above is by the way nonsense: the stability limit applies for REAL eigenvalues, for imaginary eigenvalues, forward Euler is unstable. I did the plot wrong, it is not fast-wave slow-wave but just standard IMEX with negative real part.
