### ISSUE TITLE
Problem with future module

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/pySDC#35]
When trying to run a pySDC example with
`Python 2.7.10 :: Anaconda 2.3.0 (64-bit)`
I get the following error message from the future package:

`Traceback (most recent call last):
  File "playground.py", line 10, in <module>
    from pySDC.sweeper_classes.imex_1st_order import imex_1st_order
File "/usr/not-backed-up/pySDC/pySDC/sweeper_classes/imex_1st_order.py", line 3, in <module>
    from pySDC.Sweeper import sweeper
  File "/usr/not-backed-up/pySDC/pySDC/Sweeper.py", line 7, in <module>
    from future.utils import with_metaclass
ImportError: No module named future.utils`

**Comment by pancetta** [comment]
It seems that you do not have the future package installed. Could you do a 
> conda list future

to check this?

**Comment by danielru** [comment]
Resolved by proper configuration of anaconda environment.
