### ISSUE TITLE
qDelta=PIC not giving the same result wether the sweeper is explicit or implicit

### ISSUE THREAD

**Issue by tlunet** [Parallel-in-Time/pySDC#387]
Here is an example on the Lorenz equation, using `PIC` from `generic_implicit` :

![image](https://github.com/Parallel-in-Time/pySDC/assets/12183839/2918fb8b-4d8a-4e42-814d-7ac0b910c1ec)

and `PIC` from `explicit` : 

![image](https://github.com/Parallel-in-Time/pySDC/assets/12183839/45685ee5-fab0-4c9e-bce3-7aa4c7e68389)

Is there any reason why or this should be considered as a bug ? @pancetta @brownbaerchen 

PS : 4 RADAU-RIGHT nodes, Legendre distribution, 5 sweeps

**Comment by pancetta** [comment]
Congrats, you found a bug!
