### ISSUE TITLE
Parallel modifications of the `testequation0d` class due to GPU implementations

### ISSUE THREAD

**Issue by tlunet** [Parallel-in-Time/pySDC#390]
Just realized it when merging the current [master branch](https://github.com/Parallel-in-Time/pySDC/tree/master) into the [development branch for diagonal SDC](https://github.com/caklovicka/pySDC/tree/diagonal) ...

Concerning the `TestQuation_0D.py` problem class module : 

- modifications by @brownbaerchen for CPU/GPU capabilities (https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/implementations/problem_classes/TestEquation_0D.py)
- my own modifications to avoid some issues when generating stability graph, and removal of any scipy.sparse dependencies (because why the hell do we need it :raised_eyebrow:) (https://github.com/caklovicka/pySDC/blob/diagonal/pySDC/implementations/problem_classes/TestEquation_0D.py)

Currently this generates a conflict, and there is two options :

1. do @brownbaerchen need additional modifications later on this file ? In that case I'll wait for this last modifications to merge master into my diagonal development branch, and then solve the conflicts on my side by taking into account the simplified implementation for the `testequation0d`.
2. negative answer to the previous question, then I'll solve the conflict now while ensuring that it does not brakes the changes induced for the GPU implementation

**Comment by tlunet** [comment]
btw : why do we need to have `testequation0dGPU` in a separate file ?

**Comment by brownbaerchen** [comment]
I noticed that we can remove the extra file and I planned on changing this accordingly. However, the `xp` class attribute will remain. Feel free to change the file however you want while maintaining `xp` and then I can add my touches later at some point. Or if you want I can do that tomorrow.

**Comment by tlunet** [comment]
Would prefer that you do your changes tomorrow indeed, since I won't make the PR very soon (have to finish all the article figures + problem documentation + testing before ...). 

But I would like to keep my development branch up-to-date with master, so the sooner you can do your final modifications on this file, the better for me : then I'll merge and solve the conflict on my development branch, which will be added to master once I do the PR
