### ISSUE TITLE
Numbers as integers/reals

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/pySDC#4]
Do we need to make numbers in formulas with real value output into reals, i.e. e.g.
[here](https://github.com/Parallel-in-Time/pySDC/blob/master/examples/heat1d/ProblemClass.py#L39)?

In preparing for importing pyclaw, I found an issue where the code runs properly if I change 1 to 1. there but crash with a 'division by zero' if not. The reason is that dx is zero and not set properly.

Unfortunately, I was not able to reproduce this in the python2 branch.

**Comment by pancetta** [comment]
That's a difference between Python 3 and 2, see, e.g. [here](http://nbviewer.ipython.org/github/rasbt/python_reference/blob/master/tutorials/key_differences_between_python_2_and_3.ipynb#Integer-division).

You could either use 1.0 or (which I used for porting) `from __future__ import division` in python 2.
