### ISSUE TITLE
Can we delete the (old) dedalus branch ? 

### ISSUE THREAD

**Issue by tlunet** [Parallel-in-Time/pySDC#429]
@pancetta I'm currently setting a new branch to link `pySDC` with `dedalus`, but there is already an old branch on this : https://github.com/Parallel-in-Time/pySDC/tree/dedalus

Seems it's very outdated, and the additional commits are bringing some other stuff than just dedalus thing (there is a `parallel` playground, a `pfft` one, ...) : https://github.com/Parallel-in-Time/pySDC/compare/master...dedalus

Should I try to start from this (after merging master into it, solve all eventual problems, ...) or can I simply delete this branch and restart from a clean slate ?

**Comment by pancetta** [comment]
Just wipe it and start from a clean state. I'm pretty sure I won't be able to recover anything from this anyway.

**Comment by tlunet** [comment]
:coffin: :ghost:
