### ISSUE TITLE
Make pySDC compatible with numpy 2.0

### ISSUE THREAD

**Issue by jakob-fritz** [Parallel-in-Time/pySDC#442]
There was an update to numpy 2.0, and it seem to have broken the code.

CI-Job with numpy 1.26.4: https://github.com/Parallel-in-Time/pySDC/actions/runs/9542384329/job/26297127121
CI-Job with numpy 2.0.0: https://github.com/Parallel-in-Time/pySDC/actions/runs/9577459034/job/26405728204

Some changes to the code seem to be needed to fix it.

**Comment by pancetta** [comment]
Looks like `numpy.ogrid` now returns a tuple, see [v2.0](https://numpy.org/doc/stable/reference/generated/numpy.ogrid.html) vs. [v1.25](https://numpy.org/doc/1.25/reference/generated/numpy.ogrid.html). Thoughts?

**Comment by brownbaerchen** [comment]
I suppose we just cast the tuples to list...

**Comment by brownbaerchen** [comment]
I did some fixes. If the tests pass on my fork, I will do a PR.
However, there is [this](https://github.com/Parallel-in-Time/pySDC/actions/runs/9577459034/job/26405735156) issue of some incompatibilities of numpy with matplotlib in the parallel SDC project, I think. @pancetta, why do you limit the matplotlib version? We can get rid of this limit or limit the numpy version further, I guess.

**Comment by tlunet** [comment]
Fixed with #445

**Comment by brownbaerchen** [comment]
Well, just removing plotting removes plots from the [website](https://parallel-in-time.org/pySDC/projects/parallelSDC.html)...

**Comment by pancetta** [comment]
Darn, you're right. Thoughts @tlunet ?

**Comment by tlunet** [comment]
None ... to be honest, I secretly hoped that no one would catch that :sweat_smile:

My first guess :  it's either trial and error on a separate branch to solve the deadlock, or duplicate the test without MPI, and regenerate the figures with it.

**Comment by pancetta** [comment]
If I'm not mistaken this is now [fixed](https://parallel-in-time.org/pySDC/projects/parallelSDC.html), right?

**Comment by brownbaerchen** [comment]
Guess, so. I believe @jakob-fritz implemented checks in the CI if all plots are there, so we should know if some are missing (right?)
