### ISSUE TITLE
Assert checks in Sweeper.py

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/pySDC#45]
In the constructor of `Sweeper.py`, shouldn't there be `asserts` to make sure the later used entries of `params` exist? It seems that `num_nodes` and `collocation_class` have to exist in _every_ set of parameters, independent of the underlying sweeper.

Therefore, it would make sense to check for their existence in the constructor of the sweeper class?

**Comment by danielru** [comment]
....may be we should move away from `asserts` toward an *ask for forgiveness* policy. Use `try` to attempt something, then `raise` an exception if it fails.

**Comment by pancetta** [comment]
This is fixed with the new version of pySDC. Still not asking for forgiveness, but raising errors.
