### ISSUE TITLE
u_M is not u_end

### ISSUE THREAD

**Issue by pancetta** [Parallel-in-Time/pySDC#52]
Even for Gauss-Lobatto, a simple copy from u_M to u_end is not correct, if you are picky. To reproduce a RK/collocation scheme you will have to evaluate the collocation formula in ALL cases, not just for Gauss-Legendre et al.. Fix this e.g. here: 
https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/sweeper_classes/imex_1st_order.py#L146

Does this change anything...?

**Comment by memmett** [comment]
For early iterations the integral (when the right node is 1) should be an order-of-accuracy higher than a simple copy (with all the usual caveats).

**Comment by pancetta** [comment]
Indeed. It took us a while to figure this out.. we usually do a simple
copy, if t_M = t_end, but this is not necessarily the best way to do
that. And it seems that it is mathematically more consistent to do the
collocation update every time, no matter what collocation rule we use.

**Comment by danielru** [comment]
Pull request #53 did not fix this -- the corresponding tests for Lobatto nodes are just skipped.
