### ISSUE TITLE
Integrate standard_integrators into framework

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/pySDC#67]
Adopt the class providing standard integrators to that it relies on the interface defined by the problem classes.

Collect all standard integrators at one place and implement a testing framework for them.

**Comment by danielru** [comment]
- split standard_integrators into separate classes
 - modify them so that they operate on dtypes (?)
 - accept object of type ProblemClass as argument and use its functions

**Comment by pancetta** [comment]
This is done now [here](https://github.com/Parallel-in-Time/pySDC/commit/d0471f75ec4c99900a9433049de4473676a7824b).
