### ISSUE TITLE
Move matrix generators into class derived from imex_sweeper

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/pySDC#78]
Derive a class imex_sweeper_scalar from imex_sweeper, which contains the functions to generate matrix representations of the sweeper.

Upon instantiation, this subclass should check that the attached problem is of the correct type.

**Comment by pancetta** [comment]
This may be implemented in the [matrixPFASST](https://github.com/Parallel-in-Time/pySDC/tree/master/pySDC/projects/matrixPFASST) project.. am I right?
