### ISSUE TITLE
Residual in IMEX acoustic-advection is not decreasing

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/pySDC#9]
The residual in the IMEX acoustic-advection example is not decreasing: It remains roughly at unity. The solution, however, appears to be correct.

**Comment by danielru** [comment]
Lets not talk about this unwarranted shift of blame ever again ;)

**Comment by memmett** [comment]
Clearly we're missing some exciting internal discussions... :)

**Comment by danielru** [comment]
No, no, there is nothing to see here, please move along :)
