### ISSUE TITLE
Pass time node as argument to spatial restrict/prolong routine

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/pySDC#90]
Suggest to add an argument indicating the current time node at which the solution lives to the `restrict` and `prolong` function of the [SpaceTransfer](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/core/SpaceTransfer.py) class.

This would require modification of the lines in the [BaseTransfer](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/core/BaseTransfer.py) class where these two functions are called.

Line [108](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/core/BaseTransfer.py#L108) for example would need to be changed to

`tmp_u = [self.space_transfer.restrict(F.u[0], F.sweep.coll.nodes[0])]`

correct?

Existing transfer classes would need to be modified to match the new signature, but the argument would be set to `*unused`.

**Comment by pancetta** [comment]
Yeah, well, this would spoil the splitting of space (= user realm) and time (= realm of pySDC). In most cases the user should not care "when" the space-transfer routines are called, i.e. at which point in time and before or after time-coarsening.

**Comment by danielru** [comment]
Too specialised, will be resolved by added a new class deriving from `BaseTransfer` class.
