### ISSUE TITLE
Quadrature node interpolation 

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/pySDC#92]
There seems to be an issue with interpolation between quadrature nodes if the difference in the number of nodes between levels is too large.

Running e.g. [Step 5](http://www.parallelintime.org/pySDC/tutorial/step_5.html) from the tutorial with

`sweeper_params['num_nodes'] = [7, 3]`

terminates with message

`AssertionError: ERROR: error is too high, got 0.000420431707947`

In contrast,

`sweeper_params['num_nodes'] = [3, 3]`

works fine.

**Comment by pancetta** [comment]
Well, the example you mention seems fine. The error is basically of the same order as the one we expect (4E-04 instead of 1E-04).. you're using 7 instead of 3 nodes on the fine level, so the difference could already come from this choice. Anyway, if there's a bug in the Q transfer, we'll find it (somewhere).

**Comment by pancetta** [comment]
So, if I [test](https://github.com/Parallel-in-Time/pySDC/blob/master/tests/test_Q_transfer.py#L75) this particular situation by testing to what degree polynomials are interpolated back from 2 to M nodes (M=3,...9), all seems well.

**Comment by pancetta** [comment]
Does the problem with your code also happen for MLSDC?

**Comment by danielru** [comment]
This is for the following [example](https://github.com/danielru/pySDC/blob/add/spectral_advdiff/playgrounds/ODEs/apfasst_playground.py).

Everything with `level_params['restol'] = 1E-12`. This is a scalar problem, so if `M` is the same on both levels, the problem is the same.

 - (SDC) M=7: Error: 9.700196e-12
 - (MLSDC) M=[7, 7]: Error: 1.212865e-12
 - (MLSDC) M=[7, 5]: Error: 8.938984e-13
 - (MLSDC) M=[7, 3]: Error: 1.493385e-01 (!)
 - (MLSDC) M=[7, 2]: Error: 3.760140e-01
 - (PFASST) M=[7, 7]: Error: 1.641125e-11
 - (PFASST) M=[7, 5]: Error: 1.024925e-11
 - (PFASST) M=[7,3]: Error: 2.893223e-01
 - (PFASST) M=[7,2]: Error: 2.184266e+00

It just seems odd that using `M=5` on the coarse level gives an error that is 12 orders of magnitude smaller than using `M=3`. Also, it is noteworthy that for `M=3` coarse nodes the residuals no longer go to zero. For MLSDC with `M=[7,3]`, for example, the residuals in the last step are:

Residual in iteration  1: 4.1758e-02
Residual in iteration  2: 3.6195e-02
Residual in iteration  3: 3.5732e-02
Residual in iteration  4: 3.5830e-02
Residual in iteration  5: 3.5830e-02
Residual in iteration  6: 3.5830e-02
Residual in iteration  7: 3.5830e-02
Residual in iteration  8: 3.5830e-02
Residual in iteration  9: 3.5830e-02
Residual in iteration 10: 3.5830e-02
Residual in iteration 11: 3.5830e-02
Residual in iteration 12: 3.5830e-02
Residual in iteration 13: 3.5830e-02
Residual in iteration 14: 3.5830e-02
Residual in iteration 15: 3.5830e-02

**Comment by pancetta** [comment]
I agree, there is something wrong whenever coarsening is more aggressive in the collocation.. I have to look into this.

**Comment by pancetta** [comment]
Does this happen for the standard base_transfer_class, too? Did you test this?

**Comment by pancetta** [comment]
stupid indices...

**Comment by danielru** [comment]
It is always the indices.... bad indices!
