### ISSUE TITLE
Match between fine solutions and nodes

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/pySDC#93]
In the [BaseTransfer class lines 108-110](https://github.com/Parallel-in-Time/pySDC/blob/558b2b4db3aeb97e6a87e41cd4958a8a948af37a/pySDC/core/BaseTransfer.py#L108-L110), why has `F.u` M+1 entries but `F.sweep.coll.nodes` only M? I assume that the first entry in `F.u` is the initial value, correct? This would mean we have

F.u[0] --> F.status.time (start time of time step)
F.u[1] --> F.sweep.coll.nodes[0] (first quadrature node)
F.u[2] --> F.sweep.coll.nodes[1] (second quadrature node)

etc. Is my interpretation correct?

**Comment by pancetta** [comment]
Yes, you are correct! u[0] is always the initial value and does not get changes except for incoming data within PFASST. If you do Gauss-Lobatto nodes, u[1] is equal to u[0] but will be changed by a sweep.

**Comment by danielru** [comment]
Great, thanks for the quick reply! 👍

**Comment by danielru** [comment]
Sorry, follow-up question: the values in`F.sweep.coll.nodes` are on the unit interval, right? So I will have to map them to `[F.status.time, F.status.time + F.dt]` in order to get the times of the quadrature nodes?

**Comment by pancetta** [comment]
Indeed! Add time and multiply by dt and you're good to go.
