### ISSUE TITLE
Easiest way to set tau correction to zero

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/pySDC#94]
Is there an easy way to run MLSDC/PFASST without applying the tau-correction? I am wondering what the easiest way is to set it to zero.

**Comment by pancetta** [comment]
Try to remove [this line](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/implementations/sweeper_classes/imex_1st_order.py#L91) or the corresponding one in your sweeper.

**Comment by danielru** [comment]
That seems to work. Did not fix my problem though... may be it is not FAS. Meh :(
