### ISSUE TITLE
Boris-SDC method implementation and formulas

### ISSUE THREAD

**Issue by BlackCat07** [Parallel-in-Time/pySDC#96]
Hello!

I have a question about implicit dependency in the SDC iteration.
Could you please explain how **c_k** value is defined in pySDC code? 
I expected that formula (48) (Winkel, 2015) should be used.

In pySDC **c_k** value is defined in another way by https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/implementations/sweeper_classes/boris_2nd_order.py#L108. 
After that it is transmitted to **boris_solver** at line _133_, _136_

I think there is a trick but I will be grateful for some comments.

**Comment by pancetta** [comment]
Well, it actually is formula (48): `self.S` corresponds to the second part of the right-hand side, `self.ST` is the first part (the **t**rapezoidal rule, which includes the 1/2 factor, see [here](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/implementations/sweeper_classes/boris_2nd_order.py#L53) and [here](https://github.com/Parallel-in-Time/pySDC/blob/master/pySDC/implementations/sweeper_classes/boris_2nd_order.py#L68)).

Does this make sense?

**Comment by BlackCat07** [comment]
Yes, sure! thanks for reply.
The main uncertainty was with ST matrix and 1/2 multiplier
