### ISSUE TITLE
Progressbar in HookClass fails with progressbar module v2.3

### ISSUE THREAD

**Issue by danielru** [Parallel-in-Time/pySDC#98]
E.g. lines 34 & 36 in [trajectory_HookClass.py](https://github.com/Parallel-in-Time/pySDC/blob/8fd1063ceaeed764404667a4c8f577be7a5005b0/pySDC/playgrounds/ODEs/trajectory_HookClass.py) fail with the error

`TypeError: __init__() got an unexpected keyword argument 'max_value'`

when running `vanderpol_playground.py`.

According to [here](https://github.com/ikostrikov/TensorFlow-VAE-GAN-DRAW/issues/8), the keyword now has to be `maxval` instead of `max_value`.

However, fixing this causes the code to fail in line 51 with the error

`AttributeError: next_update`

Apparently, this is also due to a change in the progressbar module: [see here](https://github.com/niltonvolpato/python-progressbar/issues/36).

**Comment by pancetta** [comment]
Try using [progressbar2](https://pypi.python.org/pypi/progressbar2).. does it help?

**Comment by danielru** [comment]
Yes, this fixes the problem. Seems kind of weird that they provide a new module that is imported the same way as the old one, though -- to clarify, still need to write
`import progressbar`
but if progressbar2 is installed, it apparently imports that instead of the old one.

**Comment by pancetta** [comment]
Great, isn't it?

**Comment by danielru** [comment]
It makes me a sad panda....
